# Generated by Django 3.0.8 on 2020-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200729_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_usa',
            new_name='fess_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_world',
            new_name='fess_in_world',
        ),
    ]
