# Generated by Django 3.0.8 on 2020-08-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200730_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_usa',
            new_name='fees_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
